# Generated by Django 5.0.3 on 2024-03-30 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=100)),
                ('brand_logo', models.CharField(max_length=100)),
                ('brand_desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Motorcycles',
            fields=[
                ('motorcycle_id', models.AutoField(primary_key=True, serialize=False)),
                ('motorcycle_name', models.CharField(max_length=100)),
                ('motorcycle_type', models.CharField(max_length=100)),
                ('motorcycle_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motorcycle_desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motorcycle.brands')),
            ],
        ),
    ]
